src/Entity/Reclamation.php
<?php

namespace App\Entity;

use App\Repository\ReclamationRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\DBAL\Types\Types;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

#[ORM\Entity(repositoryClass: ReclamationRepository::class)]
class Reclamation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;





    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "le sujet est obligatoire")]
    private ?string $sujet = null;


    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "la description est obligatoire")]
    private ?string $description_rec = null;

    #[ORM\Column(length: 255)]
    private ?string $etat = null;

    #[ORM\Column(length: 255,nullable: true)]
    private ?string $reponse;


    #[ORM\Column(length: 255)]
    private ?string $type = null;

    #[ORM\Column(type: Types::DATE_MUTABLE , nullable: true)]
    private ?\DateTimeInterface $date_rec = null;

    #[ORM\ManyToOne(inversedBy: 'reclamations')]
    private ?User $patient = null;

    #[ORM\ManyToOne(inversedBy: 'reclamations')]
    private ?User $medecin = null;





    public function getDateRec(): ?\DateTimeInterface
    {
        return $this->date_rec;
    }

    public function setDateRec(?\DateTimeInterface $date_rec): void
    {
        $this->date_rec = $date_rec;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEtat(): ?string
    {
        return $this->etat;
    }

    public function setEtat(?string $etat): void
    {
        $this->etat = $etat;
    }

    public function getReponse(): ?string
    {
        return $this->reponse;
    }

    public function setReponse(?string $reponse): void
    {
        $this->reponse = $reponse;
    }







    public function getSujet(): ?string
    {
        return $this->sujet;
    }

    public function setSujet(string $sujet): static
    {
        $this->sujet = $sujet;

        return $this;
    }

    public function getDescriptionRec(): ?string
    {
        return $this->description_rec;
    }

    public function setDescriptionRec(string $description_rec): static
    {
        $this->description_rec = $description_rec;

        return $this;
    }


    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getPatient(): ?User
    {
        return $this->patient;
    }

    public function setPatient(?User $patient): static
    {
        $this->patient = $patient;

        return $this;
    }

    public function getMedecin(): ?User
    {
        return $this->medecin;
    }

    public function setMedecin(?User $medecin): static
    {
        $this->medecin = $medecin;

        return $this;
    }

    public function __toString(): string
    {
        return $this->id;
    }


}

src/Entity/User.php
<?php

namespace App\Entity;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\DBAL\Types\Types;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    #[Assert\Email(message: "email invalid format")]
    #[Assert\NotBlank(message: " email must be non-empty")]
    private ?string $email = null;

    #[ORM\Column(nullable: true)]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    #[Assert\NotBlank(message: "password must be non-empty")]
    private ?string $password = null;
    #[Assert\EqualTo(propertyPath: "password", message: "You did not type the same password")]
    public $confirm_password;


    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "First name must be non-empty")]
    private ?string $first_name = null;

    #[ORM\Column(length: 255,)]
    #[Assert\NotBlank(message: "Last name must be non-empty")]
    private ?string $last_name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $gender = null;

    #[ORM\Column]
    #[Assert\NotBlank(message: "Tel must be non-empty")]
    #[Assert\Length(min: 8, minMessage: "minimum 8 chiffres")]
    private ?int $num_tel = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_create_compte = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $last_modify_password = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $last_modify_data = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_naissance = null;

    #[Assert\File(maxSize: "1M", mimeTypes: ["image/jpeg", "image/png"], mimeTypesMessage: "Veuillez télécharger une image au format JPG ou PNG")]
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image;



    #[ORM\Column(length: 255, nullable: true)]
    private ?string $maladie_chronique = null;

    #[ORM\Column(nullable: true)]
    private ?int $num_tel2 = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $specialite = null;

    #[ORM\Column(nullable: true)]
    private ?int $validation = null;

    #[ORM\Column(nullable: true)]
    private ?int $rate = null;



    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_debut = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_fin = null;

    #[ORM\Column(nullable: true)]
    private ?float $prix_c = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\File(maxSize: "5M", mimeTypes: ["image/jpeg", "image/png"], mimeTypesMessage: "Veuillez télécharger une image au format JPG ou PNG")]
    private ?string $diplomes = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $dure_rdv = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $allergies = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $antecedent_maladie = null;

    #[ORM\Column(length: 255, nullable: true)]
//    #[Assert\NotBlank(message:"antecedent maladie must be non-empty")]
    private ?string $antecedent_medicaux = null;



    #[ORM\Column(nullable: true)]
    private ?float $log = null;

    #[ORM\Column(nullable: true)]
    private ?float $lat = null;

    #[ORM\Column(nullable: true)]
    private ?string $pays = null;

    #[ORM\Column(nullable: true)]
    private ?string $ville = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $groupe_sanguin = null;

    #[ORM\Column]
    private ?bool $active = null;
    #[ORM\Column(nullable: true)]
    private ?bool $disponibilite = null;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;





    /**
     * @return mixed
     */
    public function getConfirmPassword()
    {
        return $this->confirm_password;
    }

    /**
     * @param mixed $confirm_password
     */
    public function setConfirmPassword($confirm_password): void
    {
        $this->confirm_password = $confirm_password;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(?string $first_name): void
    {
        $this->first_name = $first_name;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(?string $last_name): void
    {
        $this->last_name = $last_name;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(?string $gender): void
    {
        $this->gender = $gender;
    }

    public function getNumTel(): ?int
    {
        return $this->num_tel;
    }

    public function setNumTel(?int $num_tel): void
    {
        $this->num_tel = $num_tel;
    }

    public function getDateCreateCompte(): ?\DateTimeInterface
    {
        return $this->date_create_compte;
    }

    public function setDateCreateCompte(?\DateTimeInterface $date_create_compte): void
    {
        $this->date_create_compte = $date_create_compte;
    }

    public function getLastModifyPassword(): ?\DateTimeInterface
    {
        return $this->last_modify_password;
    }

    public function setLastModifyPassword(?\DateTimeInterface $last_modify_password): void
    {
        $this->last_modify_password = $last_modify_password;
    }

    public function getLastModifyData(): ?\DateTimeInterface
    {
        return $this->last_modify_data;
    }

    public function setLastModifyData(?\DateTimeInterface $last_modify_data): void
    {
        $this->last_modify_data = $last_modify_data;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(?\DateTimeInterface $date_naissance): void
    {
        $this->date_naissance = $date_naissance;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): void
    {
        $this->image = $image;
    }

    public function getMaladieChronique(): ?string
    {
        return $this->maladie_chronique;
    }

    public function setMaladieChronique(?string $maladie_chronique): void
    {
        $this->maladie_chronique = $maladie_chronique;
    }

    public function getNumTel2(): ?int
    {
        return $this->num_tel2;
    }

    public function setNumTel2(?int $num_tel2): void
    {
        $this->num_tel2 = $num_tel2;
    }

    public function getSpecialite(): ?string
    {
        return $this->specialite;
    }

    public function setSpecialite(?string $specialite): void
    {
        $this->specialite = $specialite;
    }

    public function getValidation(): ?int
    {
        return $this->validation;
    }

    public function setValidation(?int $validation): void
    {
        $this->validation = $validation;
    }

    public function getRate(): ?int
    {
        return $this->rate;
    }

    public function setRate(?int $rate): void
    {
        $this->rate = $rate;
    }

    public function getDisponibilite(): ?bool
    {
        return $this->disponibilite;
    }

    public function setDisponibilite(?bool $disponibilite): void
    {
        $this->disponibilite = $disponibilite;
    }


    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(?\DateTimeInterface $date_debut): void
    {
        $this->date_debut = $date_debut;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(?\DateTimeInterface $date_fin): void
    {
        $this->date_fin = $date_fin;
    }

    public function getPrixC(): ?float
    {
        return $this->prix_c;
    }

    public function setPrixC(?float $prix_c): void
    {
        $this->prix_c = $prix_c;
    }

    public function getDiplomes(): ?string
    {
        return $this->diplomes;
    }

    public function setDiplomes(?string $diplomes): void
    {
        $this->diplomes = $diplomes;
    }

    public function getDureRdv(): ?\DateTimeInterface
    {
        return $this->dure_rdv;
    }

    public function setDureRdv(?\DateTimeInterface $dure_rdv): void
    {
        $this->dure_rdv = $dure_rdv;
    }

    public function getAllergies(): ?string
    {
        return $this->allergies;
    }

    public function setAllergies(?string $allergies): void
    {
        $this->allergies = $allergies;
    }

    public function getAntecedentMaladie(): ?string
    {
        return $this->antecedent_maladie;
    }

    public function setAntecedentMaladie(?string $antecedent_maladie): void
    {
        $this->antecedent_maladie = $antecedent_maladie;
    }

    public function getAntecedentMedicaux(): ?string
    {
        return $this->antecedent_medicaux;
    }

    public function setAntecedentMedicaux(?string $antecedent_medicaux): void
    {
        $this->antecedent_medicaux = $antecedent_medicaux;
    }

    public function getLog(): ?float
    {
        return $this->log;
    }

    public function setLog(?float $log): void
    {
        $this->log = $log;
    }

    public function getLat(): ?float
    {
        return $this->lat;
    }

    public function setLat(?float $lat): void
    {

src/Controller/MesReclamationController.php
<?php

namespace App\Controller;
use App\Form\ReclamationType;


use App\Entity\Reclamation;
use App\Repository\ReclamationRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\RedirectResponse;


class MesReclamationController extends AbstractController
{
    #[Route('{id}/mes-reclamations', name: 'mes_reclamations')]
    public function MesReclamations(ReclamationRepository $repository, int $id): Response
    {
        $reclamations = $repository->findBy(['patient' => $id]);

        return $this->render('mes_reclamation/index.html.twig', [
            'reclamations' => $reclamations
        ]);
    }


    #[Route('/{id}/delete_reclamation/{reclamationId}', name: 'delete_reclamation')]
    public function deleteReclamation(int $id, int $reclamationId, ReclamationRepository $repository, ManagerRegistry $managerRegistry): RedirectResponse
    {
        $reclamation = $repository->find($reclamationId);

        if (!$reclamation) {
            throw $this->createNotFoundException('Réclamation non trouvée avec l\'ID : ' . $reclamationId);
        }

        $em = $managerRegistry->getManager();
        $em->remove($reclamation);
        $em->flush();

        $this->addFlash('success', 'Réclamation supprimée avec succès.');

        return $this->redirectToRoute('mes_reclamations', ['id' => $id]);
    }

    #[Route('/{id}/edit-reclamation', name: 'edit_reclamation')]
    public function editReclamation(Request $request, int $id, ReclamationRepository $reclamationRepository): Response
    {
        $reclamation = $reclamationRepository->find($id);

        if (!$reclamation) {
            throw $this->createNotFoundException('Réclamation non trouvée avec l\'ID : ' . $id);
        }

        $form = $this->createForm(ReclamationType::class, $reclamation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->flush();

            // Rediriger vers la page des réclamations avec l'ID du patient
            return $this->redirectToRoute('mes_reclamations', ['id' => $reclamation->getPatient()->getId()]);
        }

        return $this->render('mes_reclamation/edit.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}

templates/mes_reclamation/ajouterec.html.twig
{% extends 'base.html.twig' %}

{% block title %}AJouter une Reclamation{% endblock %}

{% block body %}

    <head>
        <meta charset="UTF-8">
        <title>CodePen - Finance Mobile Application-UX/UI Design Screen One</title>
        <script type="module" src="{{ asset('https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js') }}"></script>
        <script nomodule src="{{ asset('https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js') }}"></script><link rel="stylesheet" href="{{ asset('https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css') }}">
        <link rel='stylesheet' href='{{ asset('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;display=swap') }}'><link rel="stylesheet" href="{{ asset('css/stylereclamation.css') }}">
     <style>
         .field{

             height:50px;
             background: white;
             box-shadow: 0 0 2em #e6e9f9;
             padding: 1em;
             display: flex;
             flex-direction: column;
             gap: 0.5em;
             border-radius: 20px;
             color: #4d4d4d;
             margin-top: 5px;
         }
         .Desc {
             height: 200px;
             background: white;
             box-shadow: 0 0 2em #e6e9f9;
             padding: 1em;
             display: flex;
             flex-direction: column;
             gap: 0.5em;
             border-radius: 20px;
             color: #4d4d4d;
             margin-top: 5px;
             font-weight: bold;
         }

            .login{
                height: 35px;
                margin-left: 90px;
                border: none;
                border-radius: 15px;
                margin-top: 20px;
                width: 60px;
                background-color: #0cb8b6;
                color: white;
            }

     </style>
    </head>
    <body>

    <section class="hero-section d-flex justify-content-center align-items-center" id="section_1">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-12 mx-auto">
                    <h1 class="text-white text-center display-4">Explorez et Partagez vos Questions Avec Des Experts</h1>
                    <form method="get" class="custom-form mt-4 pt-2 mb-lg-0 mb-5" role="search">
                        <div class="input-group input-group-lg">
                            <span class="input-group-text bi-search" id="basic-addon1"></span>
                            <input name="keyword" type="search" class="form-control" id="keyword" placeholder="Recherchez des sujets..." aria-label="Recherche">
                            <button type="submit" class="form-control btn btn-primary">Rechercher</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <div class="screen "  style="margin-left: 40%">

        {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
        <h1>Ajouter Votre Reclamation Ici</h1>
        <div >
            <label >Nom Medecin</label>
            <div class="sec-2">
                {{ form_widget(form.medecin ,  {'attr': {'placeholder': 'Enter Nom Medecin' , 'class':'field'}}) }}
                {{ form_errors(form.medecin) }}
            </div>
        </div>
        <div >
            <label >Sujet</label>
            <div class="sec-2">
                {{ form_widget(form.sujet ,  {'attr': {'placeholder': 'Enter le Sujet' , 'class':'field'}}) }}
                {{ form_errors(form.sujet) }}
            </div>
        </div><div >
            <label >Description</label>
            <div class="sec-2">
                {{ form_widget(form.description_rec ,  {'attr': {'placeholder': 'Enter votre description' , 'class':'Desc'}}) }}
                {{ form_errors(form.description_rec) }}
            </div>
        </div>

        {{ form_widget(form.submit ,  {'attr': {'class':'login'}}) }}

    </div>
    {{ form_end(form) }}
    <!-- partial -->

    </body>
{% endblock %}

templates/mes_reclamation/delete.html.twig
{% extends 'base.html.twig' %}

{% block title %}Supprimer Réclamation{% endblock %}

{% block body %}
    <h1>Supprimer Réclamation</h1>

    <p>Êtes-vous sûr de vouloir supprimer cette réclamation ?</p>

    <form method="post" action="{{ path('delete_reclamation', {'id': reclamation.id, 'token': token}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cette réclamation ?');">
        <input type="hidden" name="_method" value="DELETE">
        <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reclamation.id) }}">
        <button type="submit" class="btn btn-danger">Supprimer</button>
    </form>
{% endblock %}

templates/mes_reclamation/detail.html.twig
<!DOCTYPE html>
<html lang="fr" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Inscription</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="../../public/css/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet"
          href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css'

    />
</head>
<body>
<header>
    <div class="container">
        <div class="row">

        </div>
        <div class="row" id="blanc">
            <div class="col l12 m12 s12" id="rectangle">
                <div class="input-field col s6">
                    <label for="prenom">Sujet</label>
                    {{ reclamation.sujet }}
                </div>
                <div class="input-field col s6">
                    <label for="nom">Medecin</label>
                    {{ reclamation.medecin.firstName ~' '~ reclamation.medecin.lastName}}
                </div>
                <div class="input-field col s12">
                    <label for="code_postal">Description</label>
                    {{ reclamation.descriptionRec }}
                </div>
                <div class="input-field col s6">
                    <label for="naissance">Date de la reclamation</label>
                    {{ reclamation.dateRec | date('Y-m-d ')}}
                </div>
                <div class="input-field col s6">
                    <label for="email">Etat</label>
                    {{ reclamation.etat}}
                </div>
                <div class="input-field col s12">
                    <label for="naissance">Reponse</label>
                    {{ reclamation.reponse }}
                </div>
            </div>
        </div>

    </div>
</header>


<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
<script type="text/javascript" src="../../public/js.js">
</script>
</body>
</html>

templates/mes_reclamation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}AJouter une Reclamation{% endblock %}

{% block body %}

    <head>
        <meta charset="UTF-8">
        <title>CodePen - Finance Mobile Application-UX/UI Design Screen One</title>
        <script type="module" src="{{ asset('https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js') }}"></script>
        <script nomodule src="{{ asset('https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js') }}"></script><link rel="stylesheet" href="{{ asset('https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css') }}">
        <link rel='stylesheet' href='{{ asset('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;display=swap') }}'><link rel="stylesheet" href="{{ asset('css/stylereclamation.css') }}">
        <style>
            .field{

                height:50px;
                background: white;
                box-shadow: 0 0 2em #e6e9f9;
                padding: 1em;
                display: flex;
                flex-direction: column;
                gap: 0.5em;
                border-radius: 20px;
                color: #4d4d4d;
                margin-top: 5px;
            }
            .Desc {
                height: 200px;
                background: white;
                box-shadow: 0 0 2em #e6e9f9;
                padding: 1em;
                display: flex;
                flex-direction: column;
                gap: 0.5em;
                border-radius: 20px;
                color: #4d4d4d;
                margin-top: 5px;
                font-weight: bold;
            }

            .login{
                height: 35px;
                margin-left: 90px;
                border: none;
                border-radius: 15px;
                margin-top: 20px;
                width: 60px;
                background-color: #0cb8b6;
                color: white;
            }

        </style>
    </head>
    <body>

    <section class="hero-section d-flex justify-content-center align-items-center" id="section_1">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-12 mx-auto">
                    <h1 class="text-white text-center display-4">Explorez et Partagez vos Questions Avec Des Experts</h1>
                    <form method="get" class="custom-form mt-4 pt-2 mb-lg-0 mb-5" role="search">
                        <div class="input-group input-group-lg">
                            <span class="input-group-text bi-search" id="basic-addon1"></span>
                            <input name="keyword" type="search" class="form-control" id="keyword" placeholder="Recherchez des sujets..." aria-label="Recherche">
                            <button type="submit" class="form-control btn btn-primary">Rechercher</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <div class="screen "  style="margin-left: 40%">

        {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
        <h1>Ajouter Votre Reclamation Ici</h1>
        <div >
            {#            <label >Nom Medecin</label>#}
            {#            <div class="sec-2">#}
            {#                {{ form_widget(form.medecin ,  {'attr': {'placeholder': 'Enter Nom Medecin' , 'class':'field'}}) }}#}
            {#                {{ form_errors(form.medecin) }}#}
            {#            </div>#}
        </div>
        <div >
            <label >Sujet</label>
            <div class="sec-2">
                {{ form_widget(form.sujet ,  {'attr': {'placeholder': 'Enter le Sujet' , 'class':'field'}}) }}
                {{ form_errors(form.sujet) }}
            </div>
        </div><div >
            <label >Description</label>
            <div class="sec-2">
                {{ form_widget(form.description_rec ,  {'attr': {'placeholder': 'Enter votre description' , 'class':'Desc'}}) }}
                {{ form_errors(form.description_rec) }}
            </div>
        </div>

        {{ form_widget(form.submit ,  {'attr': {'class':'login'}}) }}

    </div>
    {{ form_end(form) }}
    <!-- partial -->

    </body>
{% endblock %}


templates/mes_reclamation/index.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <section class="hero-section d-flex justify-content-center align-items-center" id="section_1">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-2 mx-auto">
                    <h1 class="text-white text-center display-4">Mes Réclamations</h1>
                </div>
            </div>
        </div>
    </section>
    <div class="" style="margin-top: 100px">

            <div class="row justify-content-center">
                <div class="col-md-6 mb-4">
                    <form action="{{ path('search_reclamation',{'id': id}) }}" method="GET">
                        <div class="input-group">
                            <input type="text" class="form-control" name="term" placeholder="Rechercher une réclamation...">
                            <button class="btn btn-primary" style="background-color:#0cb8b6;" type="submit">Rechercher</button>
                        </div>
                    </form>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="table-wrap">
                        <table class="table">
                            <thead class="thead-dark">
                            <tr>
                                <th>ID Réclamation</th>
                                <th>Médecin</th>
                                <th>Sujet</th>
                                <th>Etat de la reclamation</th>
                                <th>Date</th>
                                <th>Reponse</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for reclamation in reclamations %}
                                <tr class="alert" role="alert">
                                    <th scope="row">{{ reclamation.id }}</th>
                                    <td>{{ reclamation.medecin.firstName ~' '~ reclamation.medecin.lastName }}</td>
                                    <td>{{ reclamation.sujet }}</td>
                                    <td>{{ reclamation.etat }}</td>
                                    <td>{{ reclamation.dateRec | date('Y-m-d ') }}</td>
                                    {%  if reclamation.reponse %}
                                        <td>{{ reclamation.reponse }}</td>
                                    {%  else %}
                                        <td>no trouver</td>
                                        {% endif %}
                                    <td>
                                        <a href="{{ path('edit_reclamation', {'id': reclamation.id}) }}" class="btn btn-link"  style="color: #9a6e3a"
                                        >Modifier</a>
                                        <a  href="{{ path('delete_reclamation', {'id': id, 'reclamationId': reclamation.id}) }}"
                                           class="btn-link"
                                           style="color: red"
                                           onclick="return confirm('Êtes-vous sûr de vouloir supprimer cette réclamation ?');">Supprimer</a>

                                    </td>
                                </tr>
                            {% else %}
                                <tr>
                                    <td colspan="5">Aucune réclamation trouvée.</td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                            <div  class="d-flex justify-content-center mt-4">
                                <a href="{{ path('app_reclamation', {'id': id}) }}"
                                   class="btn btn-primary" style="background-color: #0cb8b6">Ajouter une nouvelle
                                    réclamation</a>
                            </div>
                    </div>
                </div>
            </div>
    </div>



{% endblock %}
{% block footer %}{% endblock %}